version: 2.1

parameters:
  docker-image:
    type: string
    default: cimg/node:14.18.0

jobs:
  build:
    docker:
      - image: << pipeline.parameters.docker-image >>
    steps:
      - checkout
      - run:
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'

  lint: 
    docker: 
      - image: << pipeline.parameters.docker-image >>
    steps:
      - checkout
      - run: 
          command: |
            echo 'Run linter check'
            npm run lint

  test: 
    docker: 
      - image: << pipeline.parameters.docker-image >>
    steps:
      - checkout
      - run: echo 'Tests must run'
          
workflows:
  build_and_test:
    jobs:
      - build
      - lint: 
         requires:
          - build
      - test: 
         requires:
          - lint